//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicDownloader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class IViewSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static IViewSettings defaultInstance = ((IViewSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IViewSettings())));
        
        public static IViewSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Favourites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Favourites"]));
            }
            set {
                this["Favourites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50, 650, 350")]
        public global::System.Drawing.Rectangle MainWindowRect {
            get {
                return ((global::System.Drawing.Rectangle)(this["MainWindowRect"]));
            }
            set {
                this["MainWindowRect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::IView.UI.Data.MainWindowState MainWindowState {
            get {
                return ((global::IView.UI.Data.MainWindowState)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumIcons")]
        public global::IView.UI.Data.ImageListViewType ImageListViewType {
            get {
                return ((global::IView.UI.Data.ImageListViewType)(this["ImageListViewType"]));
            }
            set {
                this["ImageListViewType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarVisible {
            get {
                return ((bool)(this["ToolbarVisible"]));
            }
            set {
                this["ToolbarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StatusStripVisible {
            get {
                return ((bool)(this["StatusStripVisible"]));
            }
            set {
                this["StatusStripVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExplorerDocked {
            get {
                return ((bool)(this["ExplorerDocked"]));
            }
            set {
                this["ExplorerDocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImageListDocked {
            get {
                return ((bool)(this["ImageListDocked"]));
            }
            set {
                this["ImageListDocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TasksDocked {
            get {
                return ((bool)(this["TasksDocked"]));
            }
            set {
                this["TasksDocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public global::IView.UI.Data.ImageScale AutoScale {
            get {
                return ((global::IView.UI.Data.ImageScale)(this["AutoScale"]));
            }
            set {
                this["AutoScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExplorerCollapsed {
            get {
                return ((bool)(this["ExplorerCollapsed"]));
            }
            set {
                this["ExplorerCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImageListCollapsed {
            get {
                return ((bool)(this["ImageListCollapsed"]));
            }
            set {
                this["ImageListCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TasksCollapsed {
            get {
                return ((bool)(this["TasksCollapsed"]));
            }
            set {
                this["TasksCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ExplorerSplitterDist {
            get {
                return ((int)(this["ExplorerSplitterDist"]));
            }
            set {
                this["ExplorerSplitterDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ImageListSplitterDist {
            get {
                return ((int)(this["ImageListSplitterDist"]));
            }
            set {
                this["ImageListSplitterDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int TasksSplitterDist {
            get {
                return ((int)(this["TasksSplitterDist"]));
            }
            set {
                this["TasksSplitterDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 200, 450")]
        public global::System.Drawing.Rectangle ExplorerWindowRect {
            get {
                return ((global::System.Drawing.Rectangle)(this["ExplorerWindowRect"]));
            }
            set {
                this["ExplorerWindowRect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 450, 200")]
        public global::System.Drawing.Rectangle ImageListWindowRect {
            get {
                return ((global::System.Drawing.Rectangle)(this["ImageListWindowRect"]));
            }
            set {
                this["ImageListWindowRect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 200, 450")]
        public global::System.Drawing.Rectangle TasksWindowRect {
            get {
                return ((global::System.Drawing.Rectangle)(this["TasksWindowRect"]));
            }
            set {
                this["TasksWindowRect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Properties")]
        public global::IView.UI.Data.TaskWindow SelectedTaskWindow {
            get {
                return ((global::IView.UI.Data.TaskWindow)(this["SelectedTaskWindow"]));
            }
            set {
                this["SelectedTaskWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top")]
        public global::IView.UI.Data.ToolBarPanel ToolBarPanel {
            get {
                return ((global::IView.UI.Data.ToolBarPanel)(this["ToolBarPanel"]));
            }
            set {
                this["ToolBarPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImageListToolTips {
            get {
                return ((bool)(this["ImageListToolTips"]));
            }
            set {
                this["ImageListToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public global::IView.UI.Data.ColourTable ColourTable {
            get {
                return ((global::IView.UI.Data.ColourTable)(this["ColourTable"]));
            }
            set {
                this["ColourTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int NameColumnWidth {
            get {
                return ((int)(this["NameColumnWidth"]));
            }
            set {
                this["NameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int DateColumnWidth {
            get {
                return ((int)(this["DateColumnWidth"]));
            }
            set {
                this["DateColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TypeColumnWidth {
            get {
                return ((int)(this["TypeColumnWidth"]));
            }
            set {
                this["TypeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SizeColumnWidth {
            get {
                return ((int)(this["SizeColumnWidth"]));
            }
            set {
                this["SizeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MainDisplayColour {
            get {
                return ((global::System.Drawing.Color)(this["MainDisplayColour"]));
            }
            set {
                this["MainDisplayColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HighQualityThumbnails {
            get {
                return ((bool)(this["HighQualityThumbnails"]));
            }
            set {
                this["HighQualityThumbnails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DropShadow")]
        public global::IView.Engine.Data.ThumbnailEffect ThumbnailEffect {
            get {
                return ((global::IView.Engine.Data.ThumbnailEffect)(this["ThumbnailEffect"]));
            }
            set {
                this["ThumbnailEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutomaticUpdates {
            get {
                return ((bool)(this["AutomaticUpdates"]));
            }
            set {
                this["AutomaticUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenNewWindowDoubleClick {
            get {
                return ((bool)(this["OpenNewWindowDoubleClick"]));
            }
            set {
                this["OpenNewWindowDoubleClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowConfirmOverwriteDialog {
            get {
                return ((bool)(this["ShowConfirmOverwriteDialog"]));
            }
            set {
                this["ShowConfirmOverwriteDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowImageChangesDialog {
            get {
                return ((bool)(this["ShowImageChangesDialog"]));
            }
            set {
                this["ShowImageChangesDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PropertiesToolbarVisible {
            get {
                return ((bool)(this["PropertiesToolbarVisible"]));
            }
            set {
                this["PropertiesToolbarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PropertiesHelpVisible {
            get {
                return ((bool)(this["PropertiesHelpVisible"]));
            }
            set {
                this["PropertiesHelpVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HistogramVisible {
            get {
                return ((bool)(this["HistogramVisible"]));
            }
            set {
                this["HistogramVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int HistogramHeight {
            get {
                return ((int)(this["HistogramHeight"]));
            }
            set {
                this["HistogramHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MaxFiles {
            get {
                return ((int)(this["MaxFiles"]));
            }
            set {
                this["MaxFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5242880")]
        public long MaxFileLength {
            get {
                return ((long)(this["MaxFileLength"]));
            }
            set {
                this["MaxFileLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxUndos {
            get {
                return ((int)(this["MaxUndos"]));
            }
            set {
                this["MaxUndos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRefreshHistogram {
            get {
                return ((bool)(this["AutoRefreshHistogram"]));
            }
            set {
                this["AutoRefreshHistogram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MaxWindows {
            get {
                return ((int)(this["MaxWindows"]));
            }
            set {
                this["MaxWindows"] = value;
            }
        }
    }
}
