//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1363852385_info {
            get {
                object obj = ResourceManager.GetObject("1363852385_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1363939449_netvibes {
            get {
                object obj = ResourceManager.GetObject("1363939449_netvibes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1363942937_ark2 {
            get {
                object obj = ResourceManager.GetObject("1363942937_ark2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1363960953_adept_update {
            get {
                object obj = ResourceManager.GetObject("1363960953_adept_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364078951_insert_object {
            get {
                object obj = ResourceManager.GetObject("1364078951_insert-object", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364131990_document_add {
            get {
                object obj = ResourceManager.GetObject("1364131990_document_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364150669_folder_add {
            get {
                object obj = ResourceManager.GetObject("1364150669_folder_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364155386_gtk_refresh {
            get {
                object obj = ResourceManager.GetObject("1364155386_gtk-refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364325544_stock_save_pdf_16 {
            get {
                object obj = ResourceManager.GetObject("1364325544_stock_save-pdf-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364326694_stock_save_pdf_24 {
            get {
                object obj = ResourceManager.GetObject("1364326694_stock_save-pdf_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364392872_slideshow {
            get {
                object obj = ResourceManager.GetObject("_1364392872_slideshow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410878_Add {
            get {
                object obj = ResourceManager.GetObject("_1364410878_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410881_plus_32 {
            get {
                object obj = ResourceManager.GetObject("_1364410881_plus_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410884_add1_ {
            get {
                object obj = ResourceManager.GetObject("_1364410884_add1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410887_Add {
            get {
                object obj = ResourceManager.GetObject("_1364410887_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410892_document_new {
            get {
                object obj = ResourceManager.GetObject("_1364410892_document_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410895_001_01 {
            get {
                object obj = ResourceManager.GetObject("_1364410895_001_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410898_file_add {
            get {
                object obj = ResourceManager.GetObject("_1364410898_file_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410901_add {
            get {
                object obj = ResourceManager.GetObject("_1364410901_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410906_add {
            get {
                object obj = ResourceManager.GetObject("_1364410906_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410910_edit_add {
            get {
                object obj = ResourceManager.GetObject("_1364410910_edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410914_plus {
            get {
                object obj = ResourceManager.GetObject("_1364410914_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364410919_Add_Green_Button {
            get {
                object obj = ResourceManager.GetObject("_1364410919_Add_Green_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364413350_window_new {
            get {
                object obj = ResourceManager.GetObject("_1364413350_window_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364561037_wheel {
            get {
                object obj = ResourceManager.GetObject("_1364561037_wheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364561047_wheel {
            get {
                object obj = ResourceManager.GetObject("_1364561047_wheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364561270_exit {
            get {
                object obj = ResourceManager.GetObject("1364561270_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364647743_sheduled_task {
            get {
                object obj = ResourceManager.GetObject("1364647743_sheduled_task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364647743_sheduled_task1 {
            get {
                object obj = ResourceManager.GetObject("1364647743_sheduled_task1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364647756_sheduled_task {
            get {
                object obj = ResourceManager.GetObject("1364647756_sheduled_task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364671000_10 {
            get {
                object obj = ResourceManager.GetObject("1364671000_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364710944_clear_left {
            get {
                object obj = ResourceManager.GetObject("1364710944_clear_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364711392_media_play_pause_resume {
            get {
                object obj = ResourceManager.GetObject("1364711392_media-play-pause-resume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364712905_download {
            get {
                object obj = ResourceManager.GetObject("1364712905_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364717902_list_remove {
            get {
                object obj = ResourceManager.GetObject("1364717902_list-remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364717999_delete {
            get {
                object obj = ResourceManager.GetObject("1364717999_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718151_stopwatch_start {
            get {
                object obj = ResourceManager.GetObject("1364718151_stopwatch_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718266_up {
            get {
                object obj = ResourceManager.GetObject("1364718266_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718270_go_top {
            get {
                object obj = ResourceManager.GetObject("1364718270_go-top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718320_go_bottom {
            get {
                object obj = ResourceManager.GetObject("1364718320_go-bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718322_emblem_downloads {
            get {
                object obj = ResourceManager.GetObject("1364718322_emblem-downloads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718418_checked_checkbox {
            get {
                object obj = ResourceManager.GetObject("1364718418_checked_checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718448_checkbox_unchecked {
            get {
                object obj = ResourceManager.GetObject("1364718448_checkbox_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718484_radio_unchecked {
            get {
                object obj = ResourceManager.GetObject("1364718484_radio-unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718512_to_do_list_cheked_all {
            get {
                object obj = ResourceManager.GetObject("1364718512_to_do_list_cheked_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718586_netvibes {
            get {
                object obj = ResourceManager.GetObject("1364718586_netvibes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364718804_start_here_ubuntustudio {
            get {
                object obj = ResourceManager.GetObject("1364718804_start-here-ubuntustudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364728988_file_extension_pdf {
            get {
                object obj = ResourceManager.GetObject("1364728988_file_extension_pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364729000_old_edit_find {
            get {
                object obj = ResourceManager.GetObject("1364729000_old-edit-find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364729045_Gnome_Mail_Mark_Read_32 {
            get {
                object obj = ResourceManager.GetObject("1364729045_Gnome-Mail-Mark-Read-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364729079_folderopen1 {
            get {
                object obj = ResourceManager.GetObject("1364729079_folderopen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364738251_folder_explore {
            get {
                object obj = ResourceManager.GetObject("1364738251_folder_explore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1364755245_network_support {
            get {
                object obj = ResourceManager.GetObject("1364755245_network-support", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _14747480_bang_comic_book_explosion {
            get {
                object obj = ResourceManager.GetObject("14747480-bang-comic-book-explosion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aqua_button_focus_24x24 {
            get {
                object obj = ResourceManager.GetObject("aqua_button_focus_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aqua_button_focus_24x241 {
            get {
                object obj = ResourceManager.GetObject("aqua_button_focus_24x241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aqua_button_focus_24x2411 {
            get {
                object obj = ResourceManager.GetObject("aqua_button_focus_24x2411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aqua_button_pressed_24x24 {
            get {
                object obj = ResourceManager.GetObject("aqua_button_pressed_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aqua_button_pressed_24x241 {
            get {
                object obj = ResourceManager.GetObject("aqua_button_pressed_24x241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aqua_button_pressed_24x2411 {
            get {
                object obj = ResourceManager.GetObject("aqua_button_pressed_24x2411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_16x16 {
            get {
                object obj = ResourceManager.GetObject("arrow_down_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_16x161 {
            get {
                object obj = ResourceManager.GetObject("arrow_down_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_16x1611 {
            get {
                object obj = ResourceManager.GetObject("arrow_down_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] BlankCursor {
            get {
                object obj = ResourceManager.GetObject("BlankCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cd_rom_16x16 {
            get {
                object obj = ResourceManager.GetObject("cd_rom_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cd_rom_16x161 {
            get {
                object obj = ResourceManager.GetObject("cd_rom_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cd_rom_16x1611 {
            get {
                object obj = ResourceManager.GetObject("cd_rom_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClearFiltering {
            get {
                object obj = ResourceManager.GetObject("ClearFiltering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnFilterIndicator {
            get {
                object obj = ResourceManager.GetObject("ColumnFilterIndicator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer_16x16 {
            get {
                object obj = ResourceManager.GetObject("computer_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer_16x161 {
            get {
                object obj = ResourceManager.GetObject("computer_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer_16x1611 {
            get {
                object obj = ResourceManager.GetObject("computer_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap desktop_16x16 {
            get {
                object obj = ResourceManager.GetObject("desktop_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap desktop_16x161 {
            get {
                object obj = ResourceManager.GetObject("desktop_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap desktop_16x1611 {
            get {
                object obj = ResourceManager.GetObject("desktop_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_16x16 {
            get {
                object obj = ResourceManager.GetObject("documents_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_16x161 {
            get {
                object obj = ResourceManager.GetObject("documents_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_16x1611 {
            get {
                object obj = ResourceManager.GetObject("documents_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] EyeDropperCursor {
            get {
                object obj = ResourceManager.GetObject("EyeDropperCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favourites_16x16 {
            get {
                object obj = ResourceManager.GetObject("favourites_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favourites_16x161 {
            get {
                object obj = ResourceManager.GetObject("favourites_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favourites_16x1611 {
            get {
                object obj = ResourceManager.GetObject("favourites_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Filtering {
            get {
                object obj = ResourceManager.GetObject("Filtering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_closed_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_closed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_closed_16x161 {
            get {
                object obj = ResourceManager.GetObject("folder_closed_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_closed_16x1611 {
            get {
                object obj = ResourceManager.GetObject("folder_closed_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_hidden_closed_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_hidden_closed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_hidden_closed_16x161 {
            get {
                object obj = ResourceManager.GetObject("folder_hidden_closed_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_hidden_closed_16x1611 {
            get {
                object obj = ResourceManager.GetObject("folder_hidden_closed_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_hidden_opened_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_hidden_opened_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_hidden_opened_16x161 {
            get {
                object obj = ResourceManager.GetObject("folder_hidden_opened_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_hidden_opened_16x1611 {
            get {
                object obj = ResourceManager.GetObject("folder_hidden_opened_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_opened_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_opened_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_opened_16x161 {
            get {
                object obj = ResourceManager.GetObject("folder_opened_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_opened_16x1611 {
            get {
                object obj = ResourceManager.GetObject("folder_opened_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_up_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_up_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_up_16x161 {
            get {
                object obj = ResourceManager.GetObject("folder_up_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_up_16x1611 {
            get {
                object obj = ResourceManager.GetObject("folder_up_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intended to guarantee your freedom  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GPLv2 {
            get {
                return ResourceManager.GetString("GPLv2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gtk_about {
            get {
                object obj = ResourceManager.GetObject("gtk-about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hard_drive_16x16 {
            get {
                object obj = ResourceManager.GetObject("hard_drive_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hard_drive_16x161 {
            get {
                object obj = ResourceManager.GetObject("hard_drive_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hard_drive_16x1611 {
            get {
                object obj = ResourceManager.GetObject("hard_drive_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] HistogramCross {
            get {
                object obj = ResourceManager.GetObject("HistogramCross", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] histogramcross1 {
            get {
                object obj = ResourceManager.GetObject("histogramcross1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] histogramcross11 {
            get {
                object obj = ResourceManager.GetObject("histogramcross11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Intro {
            get {
                object obj = ResourceManager.GetObject("Intro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap locked_16x16 {
            get {
                object obj = ResourceManager.GetObject("locked_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap locked_16x161 {
            get {
                object obj = ResourceManager.GetObject("locked_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap locked_16x1611 {
            get {
                object obj = ResourceManager.GetObject("locked_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_playback_start__1_ {
            get {
                object obj = ResourceManager.GetObject("media_playback_start (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_playback_stop {
            get {
                object obj = ResourceManager.GetObject("media_playback_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network_drive_16x16 {
            get {
                object obj = ResourceManager.GetObject("network_drive_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network_drive_16x161 {
            get {
                object obj = ResourceManager.GetObject("network_drive_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap network_drive_16x1611 {
            get {
                object obj = ResourceManager.GetObject("network_drive_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Image Files (*.bmp, *.gif, *.ico, *.jpe, *.jpg, *.jpeg, *.png, *.tif, *.tiff)|*.bmp;*.gif;*.ico;*.jpe;*.jpg;*.jpeg;*.png;*.tif;*.tiff|Windows Bitmap (*.bmp)|*.bmp|Graphic Interchange Format (*.gif)|*.gif|Windows Icon (*.ico)|*.ico|Joint Photographic Experts Group (*.jpe, *.jpg, *.jpeg)|*.jpe;*.jpg;*.jpeg|Portable Network Graphic (*.png)|*.png|Tagged Image File Format (*.tif, *.tiff)|*.tif;*.tff.
        /// </summary>
        internal static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap pause_16x16 {
            get {
                object obj = ResourceManager.GetObject("pause_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pictures_16x16 {
            get {
                object obj = ResourceManager.GetObject("pictures_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pictures_16x161 {
            get {
                object obj = ResourceManager.GetObject("pictures_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pictures_16x1611 {
            get {
                object obj = ResourceManager.GetObject("pictures_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play_16x16 {
            get {
                object obj = ResourceManager.GetObject("play_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ram_16x16 {
            get {
                object obj = ResourceManager.GetObject("ram_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ram_16x161 {
            get {
                object obj = ResourceManager.GetObject("ram_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ram_16x1611 {
            get {
                object obj = ResourceManager.GetObject("ram_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] RedEyeCursor {
            get {
                object obj = ResourceManager.GetObject("RedEyeCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removable_disk_16x16 {
            get {
                object obj = ResourceManager.GetObject("removable_disk_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removable_disk_16x161 {
            get {
                object obj = ResourceManager.GetObject("removable_disk_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removable_disk_16x1611 {
            get {
                object obj = ResourceManager.GetObject("removable_disk_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Bitmap (*.bmp)|*.bmp|Graphic Interchange Format (*.gif)|*.gif|Windows Icon (*.ico)|*.ico|Joint Photographic Experts Group (*.jpe, *.jpg, *.jpeg)|*.jpe;*.jpg;*.jpeg|Portable Network Graphic (*.png)|*.png|Tagged Image File Format (*.tif, *.tiff)|*.tif;*.tff.
        /// </summary>
        internal static string SaveFileFilter {
            get {
                return ResourceManager.GetString("SaveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0904199253TRUONG.
        /// </summary>
        internal static string SecureKey {
            get {
                return ResourceManager.GetString("SecureKey", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SortAscending {
            get {
                object obj = ResourceManager.GetObject("SortAscending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SortDescending {
            get {
                object obj = ResourceManager.GetObject("SortDescending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap the_marvel_universe {
            get {
                object obj = ResourceManager.GetObject("the_marvel_universe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown_drive_16x16 {
            get {
                object obj = ResourceManager.GetObject("unknown_drive_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown_drive_16x161 {
            get {
                object obj = ResourceManager.GetObject("unknown_drive_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown_drive_16x1611 {
            get {
                object obj = ResourceManager.GetObject("unknown_drive_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unlocked_16x16 {
            get {
                object obj = ResourceManager.GetObject("unlocked_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unlocked_16x161 {
            get {
                object obj = ResourceManager.GetObject("unlocked_16x161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unlocked_16x1611 {
            get {
                object obj = ResourceManager.GetObject("unlocked_16x1611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
