//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicDownloader._3rd.CassiniDev.Resources {
    using System; using System.Net;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CassiniDev {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CassiniDev() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicDownloader._3rd.CassiniDev.Resources.CassiniDev", typeof(CassiniDev).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationPath is null.
        /// </summary>
        public static string ErrApplicationPathIsNull {
            get {
                return ResourceManager.GetString("ErrApplicationPathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to startComic Downloader Internal Web Server on Port:{0} Error:{1} {2}.
        /// </summary>
        public static string ErrFailedToStartCassiniDevServerOnPortError {
            get {
                return ResourceManager.GetString("ErrFailedToStartCassiniDevServerOnPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Hostname {0}.
        /// </summary>
        public static string ErrInvalidHostname {
            get {
                return ResourceManager.GetString("ErrInvalidHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP Address {0}.
        /// </summary>
        public static string ErrInvalidIPAddress {
            get {
                return ResourceManager.GetString("ErrInvalidIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IPMode {0}.
        /// </summary>
        public static string ErrInvalidIPMode {
            get {
                return ResourceManager.GetString("ErrInvalidIPMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PortMode.
        /// </summary>
        public static string ErrInvalidPortMode {
            get {
                return ResourceManager.GetString("ErrInvalidPortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port range value {0}.
        /// </summary>
        public static string ErrInvalidPortRangeValue {
            get {
                return ResourceManager.GetString("ErrInvalidPortRangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available port found..
        /// </summary>
        public static string ErrNoAvailablePortFound {
            get {
                return ResourceManager.GetString("ErrNoAvailablePortFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is in use {0}.
        /// </summary>
        public static string ErrPortIsInUse {
            get {
                return ResourceManager.GetString("ErrPortIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port out of range: {0}.
        /// </summary>
        public static string ErrPortOutOfRange {
            get {
                return ResourceManager.GetString("ErrPortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port range end must be equal or greater than port range start {0} {1}.
        /// </summary>
        public static string ErrPortRangeEndMustBeEqualOrGreaterThanPortRangeSta {
            get {
                return ResourceManager.GetString("ErrPortRangeEndMustBeEqualOrGreaterThanPortRangeSta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.Net Version: {0}.
        /// </summary>
        public static string WebdevAspNetVersion {
            get {
                return ResourceManager.GetString("WebdevAspNetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Listing -- {0}.
        /// </summary>
        public static string WebdevDirListing {
            get {
                return ResourceManager.GetString("WebdevDirListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist..
        /// </summary>
        public static string WebdevDirNotExist {
            get {
                return ResourceManager.GetString("WebdevDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Downloader Internal Web Server failed to start listening on port {0}.
        /// Error message:
        /// {1}.
        /// </summary>
        public static string WebdevErrorListeningPort {
            get {
                return ResourceManager.GetString("WebdevErrorListeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Error {0} - {1}..
        /// </summary>
        public static string WebdevHttpError {
            get {
                return ResourceManager.GetString("WebdevHttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In memory logging is enabled. 
        ///
        ///Events are only captured when the Log window is visible 
        ///and all data will be lost when this window is closed.
        ///
        ///Install the latest System.Data.SQLite package to enable
        ///log persistence..
        /// </summary>
        public static string WebdevInMemoryLogging {
            get {
                return ResourceManager.GetString("WebdevInMemoryLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port&apos;{0}&apos;.
        /// </summary>
        public static string WebdevInvalidPort {
            get {
                return ResourceManager.GetString("WebdevInvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Downloader Internal Web Server - Port {0} - Log Viewer.
        /// </summary>
        public static string WebdevLogViewerNameWithPort {
            get {
                return ResourceManager.GetString("WebdevLogViewerNameWithPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Downloader Internal Web Server.
        /// </summary>
        public static string WebdevName {
            get {
                return ResourceManager.GetString("WebdevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Downloader Internal Web Server - Port {0}.
        /// </summary>
        public static string WebdevNameWithPort {
            get {
                return ResourceManager.GetString("WebdevNameWithPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Web Browser.
        /// </summary>
        public static string WebdevOpenInBrowser {
            get {
                return ResourceManager.GetString("WebdevOpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run ASP.NET applications locally..
        /// </summary>
        public static string WebdevRunAspNetLocally {
            get {
                return ResourceManager.GetString("WebdevRunAspNetLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error in &apos;{0}&apos; Application..
        /// </summary>
        public static string WebdevServerError {
            get {
                return ResourceManager.GetString("WebdevServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string WebdevShowDetail {
            get {
                return ResourceManager.GetString("WebdevShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string WebdevStart {
            get {
                return ResourceManager.GetString("WebdevStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string WebdevStop {
            get {
                return ResourceManager.GetString("WebdevStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Downloader Internal Web Server Usage:
        /// .
        /// </summary>
        public static string WebdevUsagestr1 {
            get {
                return ResourceManager.GetString("WebdevUsagestr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebDev.WebServer /port:&lt;port number&gt; /path:&lt;physical path&gt; [/vpath:&lt;virtual path&gt;]
        ///
        ///.
        /// </summary>
        public static string WebdevUsagestr2 {
            get {
                return ResourceManager.GetString("WebdevUsagestr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	port number:
        ///		[Optional] An unused port number between 1 and 65535.
        ///		The default is 80 (usable if you do not also have IIS listening on the same port).
        ///
        ///.
        /// </summary>
        public static string WebdevUsagestr3 {
            get {
                return ResourceManager.GetString("WebdevUsagestr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	physical path:
        ///		A valid directory name where the Web application is rooted.
        ///
        ///.
        /// </summary>
        public static string WebdevUsagestr4 {
            get {
                return ResourceManager.GetString("WebdevUsagestr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	virtual path:
        ///		[Optional] The virtual path or application root in the form of &apos;/&lt;app name&gt;&apos;.
        ///		The default is simply &apos;/&apos;.
        ///
        ///.
        /// </summary>
        public static string WebdevUsagestr5 {
            get {
                return ResourceManager.GetString("WebdevUsagestr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:
        ///WebDev.WebServer /port:8080 /path:&quot;c:\inetpub\wwwroot\MyApp&quot; /vpath:&quot;/MyApp&quot;
        ///
        ///.
        /// </summary>
        public static string WebdevUsagestr6 {
            get {
                return ResourceManager.GetString("WebdevUsagestr6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can then access the Web application using a URL of the form:
        ///	http://localhost:8080/MyApp.
        /// </summary>
        public static string WebdevUsagestr7 {
            get {
                return ResourceManager.GetString("WebdevUsagestr7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Information.
        /// </summary>
        public static string WebdevVersionInfo {
            get {
                return ResourceManager.GetString("WebdevVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Downloader Internal Web Server.
        /// </summary>
        public static string WebdevVwdName {
            get {
                return ResourceManager.GetString("WebdevVwdName", resourceCulture);
            }
        }
    }
}
